//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 03:39:54 PM CET 
//


package org.openhab.ui.cometvisu.internal.config.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionwidget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actionwidget">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;group ref="{}Infoaction_ActionWidgets"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actionwidget", propOrder = {
    "_switch",
    "toggle",
    "trigger",
    "pushbutton",
    "urltrigger",
    "multitrigger",
    "image",
    "imagetrigger",
    "pagejump",
    "page"
})
public class Actionwidget {

    @XmlElement(name = "switch")
    protected Switch _switch;
    protected Toggle toggle;
    protected Trigger trigger;
    protected Pushbutton pushbutton;
    protected Urltrigger urltrigger;
    protected Multitrigger multitrigger;
    protected Image image;
    protected Imagetrigger imagetrigger;
    protected Pagejump pagejump;
    protected Page page;

    /**
     * Gets the value of the switch property.
     * 
     * @return
     *     possible object is
     *     {@link Switch }
     *     
     */
    public Switch getSwitch() {
        return _switch;
    }

    /**
     * Sets the value of the switch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Switch }
     *     
     */
    public void setSwitch(Switch value) {
        this._switch = value;
    }

    /**
     * Gets the value of the toggle property.
     * 
     * @return
     *     possible object is
     *     {@link Toggle }
     *     
     */
    public Toggle getToggle() {
        return toggle;
    }

    /**
     * Sets the value of the toggle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Toggle }
     *     
     */
    public void setToggle(Toggle value) {
        this.toggle = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link Trigger }
     *     
     */
    public Trigger getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trigger }
     *     
     */
    public void setTrigger(Trigger value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the pushbutton property.
     * 
     * @return
     *     possible object is
     *     {@link Pushbutton }
     *     
     */
    public Pushbutton getPushbutton() {
        return pushbutton;
    }

    /**
     * Sets the value of the pushbutton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pushbutton }
     *     
     */
    public void setPushbutton(Pushbutton value) {
        this.pushbutton = value;
    }

    /**
     * Gets the value of the urltrigger property.
     * 
     * @return
     *     possible object is
     *     {@link Urltrigger }
     *     
     */
    public Urltrigger getUrltrigger() {
        return urltrigger;
    }

    /**
     * Sets the value of the urltrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Urltrigger }
     *     
     */
    public void setUrltrigger(Urltrigger value) {
        this.urltrigger = value;
    }

    /**
     * Gets the value of the multitrigger property.
     * 
     * @return
     *     possible object is
     *     {@link Multitrigger }
     *     
     */
    public Multitrigger getMultitrigger() {
        return multitrigger;
    }

    /**
     * Sets the value of the multitrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multitrigger }
     *     
     */
    public void setMultitrigger(Multitrigger value) {
        this.multitrigger = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the imagetrigger property.
     * 
     * @return
     *     possible object is
     *     {@link Imagetrigger }
     *     
     */
    public Imagetrigger getImagetrigger() {
        return imagetrigger;
    }

    /**
     * Sets the value of the imagetrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imagetrigger }
     *     
     */
    public void setImagetrigger(Imagetrigger value) {
        this.imagetrigger = value;
    }

    /**
     * Gets the value of the pagejump property.
     * 
     * @return
     *     possible object is
     *     {@link Pagejump }
     *     
     */
    public Pagejump getPagejump() {
        return pagejump;
    }

    /**
     * Sets the value of the pagejump property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagejump }
     *     
     */
    public void setPagejump(Pagejump value) {
        this.pagejump = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link Page }
     *     
     */
    public Page getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link Page }
     *     
     */
    public void setPage(Page value) {
        this.page = value;
    }

}
