//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 03:39:54 PM CET 
//


package org.openhab.ui.cometvisu.internal.config.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infoaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infoaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="layout" type="{}layout" minOccurs="0"/>
 *         &lt;element name="label" type="{}label" minOccurs="0"/>
 *         &lt;element name="infowidget" type="{}infowidget"/>
 *         &lt;element name="actionwidget" type="{}actionwidget"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoaction", propOrder = {
    "layout",
    "label",
    "infowidget",
    "actionwidget"
})
public class Infoaction {

    protected Layout layout;
    protected Label label;
    @XmlElement(required = true)
    protected Infowidget infowidget;
    @XmlElement(required = true)
    protected Actionwidget actionwidget;

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link Layout }
     *     
     */
    public Layout getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Layout }
     *     
     */
    public void setLayout(Layout value) {
        this.layout = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the infowidget property.
     * 
     * @return
     *     possible object is
     *     {@link Infowidget }
     *     
     */
    public Infowidget getInfowidget() {
        return infowidget;
    }

    /**
     * Sets the value of the infowidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Infowidget }
     *     
     */
    public void setInfowidget(Infowidget value) {
        this.infowidget = value;
    }

    /**
     * Gets the value of the actionwidget property.
     * 
     * @return
     *     possible object is
     *     {@link Actionwidget }
     *     
     */
    public Actionwidget getActionwidget() {
        return actionwidget;
    }

    /**
     * Sets the value of the actionwidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actionwidget }
     *     
     */
    public void setActionwidget(Actionwidget value) {
        this.actionwidget = value;
    }

}
